# Generated by Django 5.0.2 on 2024-02-12 02:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hierarchy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Название иерархии"),
                ),
                (
                    "criteria",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        size=None,
                        verbose_name="Критерии сравнения",
                    ),
                ),
                (
                    "alternatives",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        size=None,
                        verbose_name="Альтернативы",
                    ),
                ),
                (
                    "characteristics",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=100), size=None
                        ),
                        size=None,
                        verbose_name="Характеристика альтернатив по каждому критерию сравнения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Иерархия",
                "verbose_name_plural": "Иерархии",
            },
        ),
    ]
