# Generated by Django 5.0.2 on 2024-02-12 02:13

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hierarchies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Calculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datetime",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания расчета"
                    ),
                ),
                (
                    "calc_comparison_matrix",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=django.contrib.postgres.fields.ArrayField(
                                base_field=models.CharField(
                                    blank=True, max_length=100, null=True
                                ),
                                size=None,
                            ),
                            size=None,
                        ),
                        size=None,
                        verbose_name="Расчет матриц попарного сравнения",
                    ),
                ),
                (
                    "calc_global_priorities",
                    models.JSONField(verbose_name="Расчет глобальных приоритетов"),
                ),
                (
                    "hierarchy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hierarchies.hierarchy",
                        verbose_name="Иерархия",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Эксперт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расчет",
                "verbose_name_plural": "Расчеты",
            },
        ),
    ]
