# Generated by Django 5.0.2 on 2024-02-21 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="calculation",
            options={
                "ordering": ("-datetime",),
                "verbose_name": "Расчет",
                "verbose_name_plural": "Расчеты",
            },
        ),
    ]
